### ISSUE TITLE
relay doesnt want to run 

### ISSUE THREAD

**Issue by jackhacksren** [ftde0/yt2009relay#3]
let username = res.actions[0].openPopupAction
                                          ^

TypeError: Cannot read properties of undefined (reading '0')
    at C:\Users\jacke\Desktop\yt2009\yt2009relay\firstrun.js:87:43
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0

what do

**Comment by ftde0** [comment]
relay is no longer supported due to reliability issues. no further updates will be made.
